CREATE TABLE ADHD_Symptoms (
    id INT IDENTITY(1,1) PRIMARY KEY,
    question NVARCHAR(MAX) NOT NULL,
    adults_with_adhd_rate INT NOT NULL,
    adults_in_community_rate INT NOT NULL
);
GO

INSERT INTO ADHD_Symptoms (question, adults_with_adhd_rate, adults_in_community_rate) VALUES
('Do you find it difficult to tolerate waiting; are you impatient?', 75, 5),
('Do you make decisions impulsively?', 79, 3),
('Are you unable to inhibit your reactions or responses to events or others?', 61, 2),
('Do you have difficulty stopping your activities or behavior when you should do so?', 72, 2),
('Do you have difficulty changing your behavior when given feedback about mistakes?', 68, 4),
('Are you easily distracted by irrelevant thoughts when concentrating on something?', 96, 3),
('Are you prone to daydreaming when you should be concentrating on something?', 89, 8),
('Do you procrastinate or put off doing things until the last minute?', 94, 27),
('Do you make impulsive comments to others?', 56, 3),
('Are you likely to take shortcuts in your work and not complete all your tasks?', 65, 6),
('Are you likely to skip out on work early if it is boring or hard?', 58, 5),
('Can you defer gratification or put off doing rewarding things to work for a later goal?', 69, 2),
('Do you do things without considering the consequences?', 60, 1),
('Do you change plans at the last minute on a whim or impulse?', 72, 9),
('Do you start projects or tasks without reading or listening to directions carefully?', 89, 11),
('Do you have a poor sense of time?', 63, 3),
('Do you waste or mismanage your time?', 86, 5),
('Do you fail to consider past relevant events or experiences before responding?', 44, 1),
('Do you think less about the future compared to others your age?', 47, 8),
('Are you unprepared for work or assigned tasks?', 58, 1),
('Do you fail to meet deadlines for assignments?', 65, 1),
('Do you have trouble planning ahead or preparing for upcoming events?', 81, 6),
('Do you forget to do things you are supposed to do?', 82, 5),
('Do you have difficulties with mental arithmetic?', 55, 14),
('Are you unable to comprehend what you read as well as you should?', 81, 12),
('Can’t seem to remember what you previously heard or read about?', 77, 12),
('Can’t seem to accomplish the goals I set for myself?', 84, 7),
('Are you late for work or scheduled appointments?', 55, 5),
('Do you have trouble organizing your thoughts or thinking clearly?', 75, 2),
('Are you not aware of things you say or do?', 39, 1),
('Can’t seem to hold in mind things I need to remember to do?', 83, 7),
('Do you have difficulty being objective about things that affect you?', 64, 5),
('Do you find it hard to take other people’s perspectives about a problem or situation?', 48, 6),
('Do you have difficulty keeping in mind the purpose or goal of your activities?', 51, 1),
('Do you forget the point you were trying to make when talking to others?', 75, 2),
('When shown something complicated to do, cannot keep the information in mind to imitate or do it correctly?', 53, 1),
('Do you give poor attention to details in your work?', 60, 1),
('Do you find it difficult to keep track of several activities at once?', 68, 8),
('Can’t seem to get things done unless there is an immediate deadline?', 89, 6),
('Do you dislike work or school activities where you must think more than usual?', 60, 2),
('Do you have difficulty judging how much time it will take to do something or get somewhere?', 72, 6),
('Do you have trouble motivating yourself to start work?', 80, 6),
('Are you quick to get angry or become upset?', 63, 7),
('Are you easily frustrated?', 86, 8),
('Do you overreact emotionally?', 68, 6),
('Do you have difficulty motivating yourself to stick with your work and get it done?', 84, 4),
('Can’t seem to persist at things I do not find interesting?', 96, 13),
('Do you not put as much effort into your work as you should or as others can?', 60, 4),
('Do you have trouble staying alert or awake in boring situations?', 86, 11),
('Are you easily excited by activities going on around you?', 70, 15),
('Are you not motivated to prepare in advance for things you are supposed to do?', 80, 4),
('Can’t seem to sustain your concentration on reading, paperwork, lectures, or work?', 91, 7),
('Are you easily bored?', 81, 9),
('Do others tell you that you are lazy or unmotivated?', 57, 2),
('Do you have to depend on others to help you get your work done?', 44, 2),
('Must things have an immediate payoff for you or you don’t get them done?', 70, 2),
('Do you have trouble completing one activity before starting a new one?', 87, 7),
('Do you have difficulty resisting the urge to do something fun or more interesting when you are supposed to be working?', 87, 5),
('Can’t seem to sustain friendships or close relationships as long as others?', 46, 5),
('Are you inconsistent in the quality or quantity of your work performance?', 70, 2),
('Don’t seem to worry about future events as much as others?', 46, 10),
('Don’t think about or talk things over with yourself before doing something?', 48, 4),
('Are you unable to work as well as others without supervision or frequent instruction?', 40, 2),
('Do you have trouble doing what you tell yourself to do?', 81, 5),
('Do you show poor follow-through on promises or commitments you make to others?', 68, 3),
('Do you lack self-discipline?', 81, 5),
('Do you have difficulty using sound judgment in problem situations or when under stress?', 51, 1),
('Do you have trouble following the rules in a situation?', 61, 4),
('Are you overly rigid in how you like things done; not flexible in your behavior?', 53, 16),
('Do you have trouble organizing your thoughts?', 80, 4),
('Do you have difficulties saying what you want to say?', 70, 6),
('Are you unable to come up with or invent as many solutions to problems as others?', 37, 5),
('Are you often at a loss for words when you want to explain something to others?', 58, 5),
('Do you have trouble putting your thoughts down in writing as well or as quickly as others?', 58, 6),
('Do you feel you are not as creative or inventive as others of your intelligence level?', 27, 13),
('When trying to accomplish goals or assignments, do you fail to think of as many ways to do things as others?', 41, 5),
('Do you have trouble learning new or complex activities as well as others?', 56, 4),
('Do you have difficulty explaining things in their proper order or sequence?', 67, 1),
('Can’t seem to get to the point of your explanations as quickly as others?', 75, 9),
('Do you have trouble doing things in their proper order or sequence?', 76, 3),
('Are you unable to think on your feet or respond as effectively as others to unexpected events?', 37, 3),
('Are you clumsy or less coordinated in your movements than others?', 30, 6),
('Do you have poor or sloppy handwriting?', 63, 21),
('Do you have difficulty arranging or doing your work by its priority or importance?', 84, 4),
('Are you slower to react to unexpected events?', 37, 5),
('Do you get silly, clown around, or act foolishly when you should be serious?', 58, 4),
('Can’t seem to remember things you have done or places you have been as well as others?', 62, 14),
('Are you accident-prone?', 35, 3),
('Are you more likely to drive a motor vehicle much faster than others (excessive speeding)?', 67, 13),
('Do you have difficulties managing your money or credit cards?', 73, 8),
('Do you recall fewer events from your childhood compared to others?', 54, 25);
GO
